<?php
// Generated by server/build-football-php.mjs. Edit footballEngine.js, then regenerate.
function fbcardname($id){return ['double'=>'GOL X2','penalty'=>'PÊNALTI','shootout'=>'SHOOTOUT','suspend'=>'SUSPENSÃO'][$id];}
function fbassign($target,$values){foreach($values as $key=>$value)$target->$key=$value;return $target;}
function orderTeams($seed,$team){$order=array_values(array_diff(['podpah','capim','dendele','furia','loud','g3x','dibrados','nyvelados','fluxo','desimpain'],[$team]));for($i=count($order)-1;$i>0;$i--){$seed=($seed*1664525+1013904223)&0xffffffff;$j=(int)floor($seed/4294967296*($i+1));[$order[$i],$order[$j]]=[$order[$j],$order[$i]];}return array_slice($order,0,5);}
function campaignOrder($seed,$team){return orderTeams($seed,$team);}

define("FB_MATCH_TICKS",21600);define("FB_MAX_TICKS",200000);define("FB_STEP",(1/120));define("FB_OWN_AREA_END",240);

define('FB_cardIds',['double','penalty','shootout','suspend']);
function fbclamp($n,$a,$b){return max($a,min($b,$n));}
function fbactor($x){return (object)array_merge(["x"=>$x,"vx"=>0,"jump"=>0,"jumpV"=>0,"jumpHeld"=>false,"previousJump"=>0,"shootHeld"=>false,"shotCooldown"=>0,"specialHeld"=>false,"specialCooldown"=>0,"shield"=>0,"slow"=>0,"boost"=>0,"dash"=>0,"dashDirection"=>1,"push"=>0,"fx"=>0,"hurt"=>0,"suspended"=>0,"double"=>0,"lastHit"=>(-120),"direction"=>(($x<480)?1:(-1)),"score"=>0]);}

function fbrng($s){
$s->seed=((($s->seed*1664525)+1013904223) & 0xffffffff);
return ($s->seed/4294967296);
}

function campaignCreate($seed,$team){
$s=(object)array_merge((array)fbactor(220),["seed"=>($seed & 0xffffffff),"team"=>$team,"order"=>orderTeams($seed,$team),"rival"=>fbactor(740),"clockTick"=>0,"tick"=>0,"matchTick"=>0,"stage"=>0,"phase"=>"intro","intro"=>360,"ended"=>false,"outcome"=>null,"points"=>0,"peak"=>0,"normalGoals"=>0,"longGoals"=>0,"blowouts"=>0,"cleanSheets"=>0,"lastGoalPoints"=>0,"matchBonus"=>0,"shotOwner"=>(-1),"shotX"=>480,"score"=>0,"totalGoals"=>0,"rivalHeads"=>0,"bounces"=>0,"perfect"=>0,"bestCombo"=>0,"defeated"=>0,"goals"=>0,"against"=>0,"ball"=>(object)array_merge(["x"=>480,"y"=>280,"vx"=>0,"vy"=>0]),"lastTouch"=>(-1),"hitTick"=>(-120),"card"=>null,"rivalCard"=>null,"cardHeld"=>false,"cardUsed"=>false,"rivalCardUsed"=>false,"notice"=>"3 MINUTOS · MARQUE MAIS GOLS","noticeUntil"=>0,"chaos"=>0,"globalDouble"=>0,"goalPause"=>0,"goalSide"=>0,"setPiece"=>null,"setTicks"=>0,"setOwner"=>0,"tie"=>false,"tieRound"=>0,"tiePlayer"=>0,"tieRival"=>0,"tieScored"=>false]);
fbdeal($s);
return $s;
}

function fbdeal($s){
$s->card=FB_cardIds[floor((fbrng($s)*4))];
$s->rivalCard=FB_cardIds[floor((fbrng($s)*4))];
$s->cardUsed=false;
$s->rivalCardUsed=false;
}

function fbnotice($s,$text){
$s->notice=$text;
$s->noticeUntil=($s->tick+360);
}

function fbkickoff($s){
$playerDouble=$s->double;$rivalDouble=$s->rival->double;$playerSuspended=$s->suspended;$rivalSuspended=$s->rival->suspended;
$score=$s->score;
fbassign($s,fbactor(220));
$s->score=$score;
$s->rival=fbactor(740);
$s->double=$playerDouble;
$s->rival->double=$rivalDouble;
$s->suspended=$playerSuspended;
$s->rival->suspended=$rivalSuspended;
$s->ball=(object)array_merge(["x"=>480,"y"=>280,"vx"=>((fbrng($s)-0.5)*100),"vy"=>0]);
$s->hitTick=(-120);
$s->lastTouch=(-1);
$s->shotOwner=(-1);
$s->shotX=480;
$s->setPiece=null;
$s->setTicks=0;
$s->phase="play";
}

function fbtimers($a){
foreach(["shotCooldown","specialCooldown","shield","slow","boost","dash","fx","hurt","suspended","double"] as $k)$a->{$k}=max(0,($a->{$k}-1));
$a->push*=0.976;
if((abs($a->push)<1))$a->push=0;
}

function fbshove($a,$other,$force){
if(((!$other->shield)&&(!$other->suspended))){
$other->push=((($other->x>=$a->x)?1:(-1))*$force);
$other->hurt=30;
}
}

function fbspecial($a,$other,$team){
$a->specialCooldown=1200;
$a->fx=120;
$d=abs(($a->x-$other->x));
if((($team=="podpah")&&($d<260)))fbshove($a,$other,540);
if((($team=="capim")&&($d<140)))fbshove($a,$other,850);
if((($team=="dendele")||($team=="desimpain"))){
$a->dash=(($team=="dendele")?120:72);
$a->dashDirection=$a->direction;
if(($team=="desimpain"))$a->boost=240;
}
if((($team=="furia")||($team=="nyvelados"))){
$a->shield=(($team=="furia")?360:240);
$a->slow=0;
$a->push=0;
}
if(((($team=="loud")&&($d<320))&&(!$other->shield)))$other->slow=360;
if(($team=="g3x"))$a->boost=360;
if(($team=="dibrados")){
$a->boost=180;
$a->shield=90;
$a->push=0;
}
if((($team=="fluxo")&&($d<210))){
fbshove($a,$other,650);
if((!$other->shield))$other->slow=180;
}
}

function fbmove($a,$input,$speed){
$a->previousJump=$a->jump;
if($a->suspended){
$a->vx=0;
return ;
}
$dir=((($input->target ?? null)!=null)?fbclamp(((($input->target ?? null)-$a->x)/40),(-1),1):((int)(!(!($input->right ?? null)))-(int)(!(!($input->left ?? null)))));
if((abs($dir)>0.1))$a->direction=(($dir<0)?(-1):1);
$a->vx+=((((($dir*$speed)*($a->slow?0.5:1))*($a->boost?1.4:1))-$a->vx)*(1-exp(((-14)*FB_STEP))));
$a->x=fbclamp(($a->x+((($a->vx+$a->push)+($a->dash?($a->dashDirection*380):0))*FB_STEP)),112,848);
if(((($input->jump ?? null)&&(!$a->jumpHeld))&&($a->jump==0)))$a->jumpV=580;
$a->jumpHeld=(!(!($input->jump ?? null)));
$a->jump=max(0,($a->jump+($a->jumpV*FB_STEP)));
if(($a->jump>0))$a->jumpV-=(1150*FB_STEP);else $a->jumpV=0;
}

function fbbodies($s,$oldLeft){
$r=$s->rival;
if((($s->suspended||$r->suspended)||(abs(($s->jump-$r->jump))>116)))return false;
$left=(($oldLeft==0)?$s:$r);$right=(($oldLeft==0)?$r:$s);$overlap=(92-($right->x-$left->x));
if(($overlap<=0))return false;
$lm=($left->shield?3:1);$rm=($right->shield?3:1);
$left->x-=(($overlap*$rm)/($lm+$rm));
$right->x+=(($overlap*$lm)/($lm+$rm));
if(($left->x<112)){
$right->x+=(112-$left->x);
$left->x=112;
}
if(($right->x>848)){
$left->x-=($right->x-848);
$right->x=848;
}
$v=((($left->vx*$lm)+($right->vx*$rm))/($lm+$rm));
$left->vx=$v;
$right->vx=$v;
return true;
}

function fbkick($s,$a,$input,$owner){
if((((!($input->shoot ?? null))||$a->shotCooldown)||$a->suspended))return false;
$b=$s->ball;$dx=($b->x-$a->x);$dy=($b->y-(525-$a->jump));
if(((abs($dx)>88)||(abs($dy)>100)))return false;
$a->shotCooldown=54;
$a->lastHit=$s->tick;
$s->lastTouch=$owner;
$s->shotOwner=$owner;
$s->shotX=$a->x;
$s->hitTick=$s->tick;
$b->vx=((($owner==0)?1:(-1))*(580+(abs($a->vx)*0.25)));
$b->vy=(($a->jump>20)?(-310):(-190));
return true;
}

function fbstartPiece($s,$owner,$kind){
$pscore=$s->score;
fbassign($s,fbactor((($owner==0)?(($kind=="penalty")?650:480):150)));
$s->score=$pscore;
$s->rival=fbactor((($owner==1)?(($kind=="penalty")?310:480):810));
$s->setPiece=$kind;
$s->setOwner=$owner;
$s->setTicks=600;
$s->phase="setpiece";
$s->hitTick=(-120);
$s->lastTouch=(-1);
$s->shotOwner=(-1);
$s->shotX=480;
$s->tieScored=false;
$s->ball=(object)array_merge(["x"=>(($owner==0)?($s->x+50):($s->rival->x-50)),"y"=>530,"vx"=>0,"vy"=>0]);
fbnotice($s,((($owner==0)?"SUA COBRANÇA: ":"RIVAL COBRA: ").(($kind=="penalty")?"PÊNALTI":"SHOOTOUT")));
}

function fbuseCard($s,$owner){
$key=(($owner==0)?"card":"rivalCard");$used=(($owner==0)?"cardUsed":"rivalCardUsed");
if((((((($owner==0)?$s:$s->rival)->suspended||$s->{$used})||($s->matchTick<3600))||($s->phase!="play"))||($s->matchTick>=21000)))return false;
$s->{$used}=true;
$a=(($owner==0)?$s:$s->rival);$other=(($owner==0)?$s->rival:$s);
if(($s->{$key}=="double"))$a->double=1800;
if(($s->{$key}=="suspend")){
$other->suspended=720;
$other->vx=0;
$other->push=0;
}
if((($s->{$key}=="penalty")||($s->{$key}=="shootout")))fbstartPiece($s,$owner,$s->{$key});else fbnotice($s,((($owner==0)?"SUA CARTA: ":"CARTA DO RIVAL: ").fbcardname($s->{$key})));
return true;
}

function fbai($s){
$b=$s->ball;$r=$s->rival;
$target=fbclamp((($b->x+42)+($b->vx*0.12)),130,835);
if((($s->phase=="setpiece")&&($s->setOwner==0)))$target=810;
$attackingPiece=(($s->phase=="setpiece")&&($s->setOwner==1));
$jump=($attackingPiece?(($s->setTicks<540)&&($r->jump==0)):((((($b->y<465)&&($b->vy>0))&&(abs(($b->x-$r->x))<90))&&($r->jump==0))&&(($s->tick%60)<8)));
return (object)array_merge(["target"=>$target,"jump"=>$jump,"shoot"=>($attackingPiece?(($r->jump>25)&&($r->jump<90)):(($s->tick%(($s->stage<2)?100:76))<5)),"special"=>(($s->tick%1100)==600)]);
}

function fbballStep($s){
$b=$s->ball;$r=$s->rival;$dt=(FB_STEP/3);
$event=null;
for($step=0;($step<3);$step++){
$oldX=$b->x;$oldY=$b->y;
$b->vy+=((($s->chaos==1)?420:720)*$dt);
$b->x+=($b->vx*$dt);
$b->y+=($b->vy*$dt);
if(($b->y<150)){
$b->y=150;
$b->vy=(abs($b->vy)*0.8);
}
if(($b->y>=546)){
$b->y=546;
$b->vy=(-max(150,(abs($b->vy)*0.65)));
$b->vx*=0.94;
if(($step==0)){
$s->bounces++;
$event="ground";
}
}
if(((($b->y-14)>=380)&&(($b->y+14)<=560))){
if(((($oldX+14)>=80)&&(($b->x+14)<80)))return "goal-rival";
if(((($oldX-14)<=880)&&(($b->x-14)>880)))return "goal-player";
}
if(((((($b->x<80)||($b->x>880))&&($b->vy>0))&&(($oldY+14)<=380))&&(($b->y+14)>=380))){
$b->y=366;
$b->vy=((-abs($b->vy))*0.7);
$event="post";
}
foreach([80,880] as $gx){
if(((abs(($b->x-$gx))<17)&&(abs(($b->y-380))<18))){
$b->x=$oldX;
$b->y=$oldY;
$b->vx*=(-0.8);
$b->vy*=(-0.65);
$event="post";
}
}
if((($b->x<25)||($b->x>935))){
$b->x=fbclamp($b->x,25,935);
$b->vx*=(-0.82);
}
for($owner=0;($owner<2);$owner++){
$a=(($owner==0)?$s:$r);
if(($a->suspended||(($s->lastTouch==$owner)&&(($s->tick-$s->hitTick)<16))))continue;
$dx=($b->x-$a->x);$head=(450-$a->jump);
if(((((abs($dx)<43)&&($b->vy>0))&&($oldY<=($head-20)))&&($b->y>=($head-29)))){
$b->y=($head-30);
$b->vx=((($owner==0)?1:(-1))*(340+(abs($dx)*3)));
$b->vy=((-210)-(max(0,$a->jumpV)*0.16));
$s->lastTouch=$owner;
$s->shotOwner=$owner;
$s->shotX=$a->x;
$s->hitTick=$s->tick;
$a->lastHit=$s->tick;
$event=(($owner==0)?"hit":"rival-hit");
continue;
}
$nearX=fbclamp($b->x,($a->x-30),($a->x+30));$nearY=fbclamp($b->y,($head-10),(550-$a->jump));
$nx=($b->x-$nearX);$ny=($b->y-$nearY);$dist=sqrt((($nx*$nx)+($ny*$ny)));
if((($dist<14)&&($dist>0.001))){
$b->x=($nearX+(($nx/$dist)*14));
$b->y=($nearY+(($ny/$dist)*14));
$dot=((($b->vx*$nx)/$dist)+(($b->vy*$ny)/$dist));
if(($dot<0)){
$s->shotOwner=$owner;
$s->shotX=$a->x;
$b->vx-=(((1.7*$dot)*$nx)/$dist);
$b->vy-=(((1.7*$dot)*$ny)/$dist);
$b->vx+=($a->vx*0.3);
}
}
}
$b->vx=fbclamp($b->vx,(-950),950);
$b->vy=fbclamp($b->vy,(-800),800);
}
return $event;
}

function fbendCampaign($s,$outcome){
$s->ended=true;
$s->outcome=$outcome;
$s->phase="ended";
$s->peak=max($s->peak,$s->points);
return "end";
}

function fbfinishMatch($s,$won){
if((!$won))return fbendCampaign($s,"lose");
$s->matchBonus=0;
if((($s->goals-$s->against)>=3)){
$s->blowouts++;
$s->matchBonus+=100;
}
if(($s->against==0)){
$s->cleanSheets++;
$s->matchBonus+=20;
}
$s->defeated++;
$s->points+=$s->matchBonus;
$s->peak=$s->points;
if(($s->stage==4))return fbendCampaign($s,"win");
$s->stage++;
$s->goals=0;
$s->against=0;
$s->matchTick=0;
$s->tie=false;
$s->tieRound=0;
$s->tiePlayer=0;
$s->tieRival=0;
$s->globalDouble=0;
$s->chaos=0;
$s->double=0;
$s->rival->double=0;
$s->suspended=0;
$s->rival->suspended=0;
fbkickoff($s);
fbdeal($s);
$s->phase="intro";
$s->intro=360;
return "next";
}

function fbnextTie($s){
$s->tieRound++;
if((((($s->tieRound%2)==0)&&($s->tieRound>=6))&&($s->tiePlayer!=$s->tieRival)))return fbfinishMatch($s,($s->tiePlayer>$s->tieRival));
if(($s->tieRound>=20))return fbendCampaign($s,"draw");
fbstartPiece($s,($s->tieRound%2),"shootout");
return "shootout";
}

function fbscoreGoal($s,$owner){
if($s->tie){
if(($owner==$s->setOwner)){
if(($owner==0))$s->tiePlayer++;else $s->tieRival++;
}
$s->tieScored=true;
}else {
$mult=(($s->globalDouble||((($owner==0)?$s:$s->rival)->double>0))?2:1);
if(($owner==0)){
$s->goals+=$mult;
$s->totalGoals++;
$s->score=$s->totalGoals;
$long=(($s->shotOwner==0)&&($s->shotX<=FB_OWN_AREA_END));
$s->lastGoalPoints=($long?30:20);
if($long)$s->longGoals++;else $s->normalGoals++;
$s->points+=$s->lastGoalPoints;
$s->peak=$s->points;
}else $s->against+=$mult;
}
$s->goalSide=$owner;
$s->goalPause=180;
$s->phase="goal";
fbnotice($s,(($owner==0)?"GOOOL!":"GOL DO RIVAL"));
return (($owner==0)?"goal":"rival-goal");
}

function campaignAdvance($s,$input=null){
if($s->ended)return null;
$s->clockTick++;
if(($s->phase=="intro")){
if((--$s->intro<=0)){
$s->phase="play";
return "ready";
}
return null;
}
$s->tick++;
if((!$s->tie))$s->matchTick++;
$event=null;
if((((!$s->tie)&&($s->matchTick>=FB_MATCH_TICKS))&&($s->phase!="goal"))){
if(($s->goals!=$s->against))return fbfinishMatch($s,($s->goals>$s->against));
$s->tie=true;
$s->tieRound=0;
$s->tiePlayer=0;
$s->tieRival=0;
fbstartPiece($s,0,"shootout");
fbnotice($s,"EMPATE! SHOOTOUTS · MELHOR DE 3");
return "shootout";
}
if(($s->matchTick==3600)){
fbnotice($s,"CARTAS LIBERADAS! USE Q OU O BOTÃO");
$event="card-ready";
}
if(($s->matchTick==7200)){
$s->globalDouble=1800;
fbnotice($s,"1:00 · GOL X2 PARA OS DOIS POR 15s");
$event="surprise";
}
if(($s->matchTick==10800)){
$s->chaos=(1+floor((fbrng($s)*2)));
fbnotice($s,(($s->chaos==1)?"INTERVALO · BOLA LEVE POR 15s":"INTERVALO · TURBO PARA OS DOIS POR 15s"));
$event="surprise";
}
if(($s->matchTick==12600))$s->chaos=0;
if(($s->matchTick==13200)){
fbdeal($s);
fbnotice($s,"NOVAS CARTAS PARA O SEGUNDO TEMPO");
$event="card-ready";
}
if(($s->matchTick==18000)){
$s->globalDouble=3600;
fbnotice($s,"RETA FINAL · TODOS OS GOLS VALEM X2!");
$event="surprise";
}
if(($s->phase=="goal")){
$s->ball->x=fbclamp(($s->ball->x+(($s->ball->vx*FB_STEP)*0.15)),30,930);
$s->ball->vx*=0.96;
if((--$s->goalPause<=0)){
if($s->tie)return fbnextTie($s);
fbkickoff($s);
return "ready";
}
return null;
}
fbtimers($s);
fbtimers($s->rival);
if(($s->globalDouble>0))$s->globalDouble--;
if(((($input->card ?? null)&&(!$s->cardHeld))&&fbuseCard($s,0)))$event="card";
$s->cardHeld=(!(!($input->card ?? null)));
if(((($s->phase=="play")&&((($s->matchTick>=(4800+($s->stage*137)))&&($s->matchTick<13200))||($s->matchTick>=(15000+($s->stage*113)))))&&fbuseCard($s,1)))$event="rival-card";
$r=$s->rival;$control=fbai($s);$left=(($s->x<=$r->x)?0:1);
$playerInput=($s->suspended?(object)array_merge([]):$input);
fbmove($s,$playerInput,(360*(($s->chaos==2)?1.25:1)));
fbmove($r,$control,((260+($s->stage*18))*(($s->chaos==2)?1.25:1)));
if(($s->phase=="setpiece")){
$keeper=(($s->setOwner==0)?$r:$s);
$keeper->x=(($s->setOwner==0)?810:150);
if(($s->setPiece=="penalty")){
$shooter=(($s->setOwner==0)?$s:$r);
$shooter->x=(($s->setOwner==0)?650:310);
}
}
if((fbbodies($s,$left)&&(($s->tick%48)==0)))$event="bump";
if(((((($input->special ?? null)&&(!$s->specialHeld))&&(!$s->specialCooldown))&&(!$s->suspended))&&($s->phase=="play"))){
fbspecial($s,$r,$s->team);
$event="special";
}
$s->specialHeld=(!(!($input->special ?? null)));
if(((($control->special&&(!$r->specialCooldown))&&(!$r->suspended))&&($s->phase=="play"))){
fbspecial($r,$s,$s->order[$s->stage]);
$event="rival-special";
}
if(fbkick($s,$s,$playerInput,0))$event="kick";
if(fbkick($s,$r,$control,1))$event="rival-kick";
$ballEvent=fbballStep($s);
if((($ballEvent=="goal-player")||($ballEvent=="goal-rival"))){
$owner=(($ballEvent=="goal-player")?0:1);
if((($s->phase=="setpiece")&&($owner!=$s->setOwner))){
if($s->tie)return fbnextTie($s);
fbkickoff($s);
return "ready";
}
return fbscoreGoal($s,$owner);
}
if($ballEvent)$event=$ballEvent;
if((($s->phase=="setpiece")&&(--$s->setTicks<=0))){
if($s->tie)return fbnextTie($s);
fbkickoff($s);
fbnotice($s,"COBRANÇA ENCERRADA · BOLA EM JOGO");
return "ready";
}
return $event;
}

function campaignResult($s){
return (object)array_merge(["normalGoals"=>$s->normalGoals,"longGoals"=>$s->longGoals,"blowouts"=>$s->blowouts,"cleanSheets"=>$s->cleanSheets,"score"=>$s->totalGoals,"points"=>$s->points,"peak"=>$s->peak,"defeated"=>$s->defeated,"stage"=>$s->stage,"outcome"=>$s->outcome,"duration"=>(round(($s->tick/12))/10),"clockTick"=>$s->clockTick,"ended"=>$s->ended,"goals"=>$s->goals,"against"=>$s->against,"tiePlayer"=>$s->tiePlayer,"tieRival"=>$s->tieRival,"matchTick"=>$s->matchTick]);
}

function campaignVerify(int $seed,string $team,mixed $inputs,mixed $tick): array {
 if(!is_int($tick)||$tick<1||$tick>FB_MAX_TICKS||!is_array($inputs)||!array_is_list($inputs)||count($inputs)>$tick)throw new InvalidArgumentException('Replay invalido');
 $last=-1;
 foreach($inputs as $entry){
  if(!is_array($entry)||!is_int($entry['tick']??null)||$entry['tick']<0||$entry['tick']<=$last||$entry['tick']>=$tick)throw new InvalidArgumentException('Tick invalido');
  foreach(['left','right','jump','special','shoot','card'] as $key)if(!isset($entry[$key])||!is_bool($entry[$key]))throw new InvalidArgumentException('Controle invalido');
  if(!array_key_exists('target',$entry)||($entry['target']!==null&&(!is_int($entry['target'])||$entry['target']<38||$entry['target']>922)))throw new InvalidArgumentException('Alvo invalido');
  $last=$entry['tick'];
 }
 $s=campaignCreate($seed,$team);$i=0;$control=(object)['left'=>false,'right'=>false,'jump'=>false,'special'=>false,'shoot'=>false,'card'=>false,'target'=>null];
 while($s->clockTick<$tick&&!$s->ended){if(isset($inputs[$i])&&$inputs[$i]['tick']===$s->clockTick)$control=(object)$inputs[$i++];campaignAdvance($s,$control);}
 if($s->clockTick!==$tick||$i!==count($inputs))throw new InvalidArgumentException('Partida encerrada');
 return (array)campaignResult($s);
}
