CREATE TABLE IF NOT EXISTS game_football_runs (
 id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 user_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 seed BIGINT UNSIGNED NOT NULL,
 team VARCHAR(20) NOT NULL,
 engine_version SMALLINT UNSIGNED NOT NULL DEFAULT 7,
 last_tick INT UNSIGNED NOT NULL DEFAULT 0,
 status VARCHAR(12) NOT NULL DEFAULT 'active',
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX (user_id, status), INDEX (created_at),
 FOREIGN KEY (user_id) REFERENCES game_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS game_football_records (
 user_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 team VARCHAR(20) NOT NULL,
 points INT UNSIGNED NOT NULL DEFAULT 0,
 score INT UNSIGNED NOT NULL DEFAULT 0,
 defeated INT UNSIGNED NOT NULL DEFAULT 0,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX (points, score),
 FOREIGN KEY (user_id) REFERENCES game_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game_football_team_records (
 user_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 team VARCHAR(20) NOT NULL,
 points INT UNSIGNED NOT NULL DEFAULT 0,
 score INT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (user_id, team),
 CONSTRAINT game_football_team_user_fk FOREIGN KEY (user_id) REFERENCES game_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
